version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "database_passw"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    image: abys72/ordiscloud-api
    environment:
      DATABASE_USER: postgres
      PASSWORD_USER: "database_passw"
      DATABASE: postgres
      DATABASE_HOST: db
      PORT_API: 443
      SSL_CERTIFICATE: /etc/ssl/certs/cert.pem
      SSL_PRIVATE_KEY: /etc/ssl/certs/private.pem
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/ssl:/etc/ssl/certs
    depends_on:
      - db
volumes:
  db_data:
